services:
  _defaults:
    autowire: true

  Johannes85\AiBundle\LLM\Ollama\Examples\:
    resource: '../src/LLM/Ollama/Examples'
    public: true;

  Johannes85\AiBundle\LLM\OpenAi\Examples\:
    resource: '../src/LLM/Ollama/Examples'
    public: true;

  Johannes85\AiBundle\LLM\Ollama\Ollama:
    arguments:
      $endpoint: 'http://127.0.0.1:11434'
      $model: 'gemma2'

  Johannes85\AiBundle\LLM\OpenAi\OpenAi:
    arguments:
      $apiKey: 'xxx'
      $model: 'gpt-4o-mini'
