services:
  _defaults:
    autowire: true

  ai_bundle.examples.cache.filesystem_adapter:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      $namespace: 'ai_bundle_examples'

  AiBundle\Prompting\MessageStore\Psr6CacheMessageStore:
    arguments:
      $cache: '@ai_bundle.examples.cache.filesystem_adapter'
      $ttl: 3600

  AiBundle\Examples\:
    resource: '../src/Examples'
    public: true;

  AiBundle\LLM\Ollama\Examples\:
    resource: '../src/LLM/Ollama/Examples'
    public: true;

  AiBundle\LLM\OpenAi\Examples\:
    resource: '../src/LLM/Ollama/Examples'
    public: true;

  AiBundle\LLM\GoogleAi\Examples\:
    resource: '../src/LLM/Ollama/Examples'
    public: true;

  AiBundle\LLM\Anthropic\Examples\:
    resource: '../src/LLM/Anthropic/Examples'
    public: true;

  AiBundle\LLM\Ollama\Ollama:
    arguments:
      $endpoint: 'http://127.0.0.1:11434'
      $model: 'gemma3:latest'

  AiBundle\LLM\OpenAi\OpenAi:
    arguments:
      $apiKey: '...'
      $model: 'gpt-4o-mini'

  AiBundle\LLM\GoogleAi\GoogleAi:
    arguments:
      $apiKey: '...'
      $model: 'gemini-2.0-flash'

  AiBundle\LLM\Anthropic\Anthropic:
    arguments:
      $apiKey: '...'
      $model: 'claude-3-5-sonnet-20241022'

