services:
  _defaults:
    autowire: true

  ai_bundle.examples.cache.filesystem_adapter:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      $namespace: 'ai_bundle_examples'

  AiBundle\Prompting\MessageStore\Psr6CacheMessageStore:
    arguments:
      $cache: '@ai_bundle.examples.cache.filesystem_adapter'
      $ttl: 3600

  AiBundle\Examples\:
    resource: '../src/Examples'
    public: true;

  ai_bundle.llm.ollama:
    public: true
    class: AiBundle\LLM\Ollama\Ollama
    arguments:
      $endpoint: 'http://127.0.0.1:11434'
      $model: 'gemma3:12b'
      $timeout: 300

  ai_bundle.llm.open_ai:
    public: true
    class: AiBundle\LLM\OpenAi\OpenAi
    arguments:
      $endpoint: 'https://api.openai.com/v1'
      $apiKey: '%env(string:OPEN_AI_APIKEY)%'
      $model: 'gpt-4o-mini'
      $timeout: 300

  ai_bundle.llm.google_ai:
    public: true
    class: AiBundle\LLM\GoogleAi\GoogleAi
    arguments:
      $apiKey: '%env(string:GOOGLE_AI_APIKEY)%'
      $model: 'gemini-2.0-flash'
      $timeout: 300

  ai_bundle.llm.anthropic:
    public: true
    class: AiBundle\LLM\Anthropic\Anthropic
    arguments:
      $apiKey: '%env(string:ANTHROPIC_APIKEY)%'
      $model: 'claude-3-5-sonnet-20241022'
      $timeout: 300

  ai_bundle.llm.mistral_ai:
    public: true
    class: AiBundle\LLM\MistralAi\MistralAi
    arguments:
      $apiKey: '%env(string:MISTRAL_AI_APIKEY)%'
      $model: 'mistral-small-latest'
      $timeout: 300
