services:
  _defaults:
    autowire: true

  AiBundle\LLM\Ollama\Examples\:
    resource: '../src/LLM/Ollama/Examples'
    public: true;

  AiBundle\LLM\OpenAi\Examples\:
    resource: '../src/LLM/Ollama/Examples'
    public: true;

  AiBundle\LLM\GoogleAi\Examples\:
    resource: '../src/LLM/Ollama/Examples'
    public: true;

  AiBundle\LLM\Ollama\Ollama:
    arguments:
      $endpoint: 'http://127.0.0.1:11434'
      $model: 'gemma2'

  AiBundle\LLM\OpenAi\OpenAi:
    arguments:
      $apiKey: '...'
      $model: 'gpt-4o-mini'

  AiBundle\LLM\GoogleAi\GoogleAi:
    arguments:
      $apiKey: '...'
      $model: 'gemini-2.0-flash'

